### ISSUE TITLE
if user tries !rank SEA, have msg saying "Sorry Captain, this is the Global server! Only NA and EU. Please refrain from getting these roles just for color. You are still able to join us with just Captain rank"

### ISSUE THREAD

**Issue by YuraInoue** [HI3-Discord/ai-chan#12]

**Comment by ikuyarihS** [comment]
This can be easily done by adding another role on the spreadsheet and call it `SEA` - make it not joinable and use this as the join message.

**Comment by ikuyarihS** [comment]
I've added the role and the message.

This is what it looks like:
![image](https://user-images.githubusercontent.com/19921765/77818382-7251e900-7104-11ea-9530-0894b80511e6.png)
