### ISSUE TITLE
"❌ Captain @__, you can only have 1 role among: NA, EU" provide instructions on how to remove the role "To remove your role, please !rank (your assigned role NA or EU)."

### ISSUE THREAD

**Issue by YuraInoue** [HI3-Discord/ai-chan#15]

**Comment by ikuyarihS** [comment]
Done in https://github.com/ikuyarihS/ai-chan-py/commit/dae7de17f9f10483fe5270ec3e734d4ba0a1886a

![image](https://user-images.githubusercontent.com/19921765/77842662-4ba4b880-71bf-11ea-9e35-d58e46eecc85.png)

![image](https://user-images.githubusercontent.com/19921765/77842665-595a3e00-71bf-11ea-8e64-292354197a34.png)
