### ISSUE TITLE
When detecting image spam, only delete images past the spam limit

### ISSUE THREAD

**Issue by PaeP3nguin** [HI3-Discord/ai-chan#21]
It's pretty common for noobs to post a bunch of images, but it may be nicer to only delete images past the spam limit instead of deleting all images from the user. For example, if the limit is 3 images, just delete the 4th image onwards

**Comment by ikuyarihS** [comment]
That's a good one, I will have to do more logic checking but it should be more pleasant and won't be as scary to hit the attachments limit.

I will make this change when I completely move filter from jschan to pychan.

**Comment by ikuyarihS** [comment]
This has been done!

Now pychan will only delete messages that go over the limit.
