### ISSUE TITLE
add !rank asia to "Sorry Captain, this is the Global server! Only NA and EU. Please refrain from getting these roles just for color. You are still able to join us with just Captain rank"

### ISSUE THREAD

**Issue by YuraInoue** [HI3-Discord/ai-chan#27]

**Comment by YuraInoue** [comment]
also !rank cn, !rank china, !rank jp, !rank japan, !rank tw, !rank taiwan, !rank kr, !rank korea

**Comment by ikuyarihS** [comment]
This can be done easily via the spreadsheet and then reload the assign_rank cog via `!reloadext assign_rank` - You can do that Yura

![image](https://user-images.githubusercontent.com/19921765/78873319-dcf41480-7a74-11ea-8c89-0c834995c130.png)

I've added then to the spreadsheet and reloaded the cog:

![image](https://user-images.githubusercontent.com/19921765/78873402-044ae180-7a75-11ea-88db-8bfcadf678db.png)

![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/19921765/78873492-2b091800-7a75-11ea-82e6-8f7df2aa9635.png)
